config/routes.rb
Rails.application.routes.draw do
    resources :notes, :except => :show do
        collection do
            post :confirm
            get :top
        end
    end
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
    validates :content, presence: true, length: {maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :set_notes, only: [:edit, :destroy]
    
    def index
        @note = Note.all
    end
    
    def create
        @note = Note.new(note_params)
        if @note.save
            redirect_to new_note_path, notice:"投稿しました！"
        else
            render 'new'
        end
    end
    
    def new
        if params[:back]
            @note = Note.new(note_params)
        else
            @note = Note.new
        end
    end
    
    def edit
    end
    
    def update
        @note = Note.find(params[:id])
        if @note.update(note_params)
            redirect_to notes_path, notice:"編集しました！"
        else
            render 'edit'
        end
    end
    
    def destroy
        @note.destroy
        redirect_to notes_path, notice:"削除しました！"
    end
    
    def confirm
        @note = Note.new(note_params)
        render :new if @note.invalid?
    end
    
    def top
    end
    
    private
    def note_params
        params.require(:note).permit(:content)
    end
    
    def set_notes
        @note = Note.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
    def new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_notes_path
        elsif action_name == 'edit'
            note_path
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TNote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <ul class="top_menu">
        <li><%= link_to 't-Note', top_notes_path, :class => "sitename" %></li>
        <li><%= link_to 'Home', top_notes_path, :class => "menu" %></li>
        <li><%= link_to '新規投稿', new_note_path, :class => "menu" %></li>
        <li><%= link_to '投稿一覧', notes_path, :class => "menu" %></li>
      </ul>
    </header>
    
    <div class="main">
      <%= yield %>
    </div>
    
    <footer class="footer">
      <p>clone application</p>
    </footer>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model:@note, local:true, url:new_or_edit) do |form| %>
    <% if @note.errors.any? %>
        <div class="errors_area">
            <ul>
                <% @note.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="form_area">
        <%= form.label :content, :class => "form_label" %>
        <%= form.text_field :content %>
        <%= form.submit "投稿", :class => "submit" %>
    </div>
<% end %>

app/views/notes/confirm.html.erb
<h2 class="index">確認画面</h2>

<div class="form_area">
<%= form_with(model:@note, url:notes_path, local:true) do |form| %>
    <%= form.hidden_field:content %>
        <%= @note.content %>
        <%= form.submit "投稿", :class => "submit" %>
<% end %>

<%= form_with(model:@note, url:new_note_path, local:true, method:'get') do |form| %>
    
        <%= form.hidden_field:content %>
        <%= form.submit "戻る", name: 'back', :class => "submit back_submit" %>
<% end %>
</div>

app/views/notes/edit.html.erb
<h2 class="index">編集画面</h2>

<%= render 'form' %>

app/views/notes/index.html.erb
<h2 class="index">投稿一覧</h2>

<p><%= notice %></p>

<table class="index_area">
<% @note.each do |note| %>
    <tr>
        <td class="index_content"><%= note.content %></td>
        <td>
            <button name="button" type="submit" class="index_submit edit_submit">
                <%= link_to '編集', edit_note_path(note.id) %>
            </button>
        </td>
        <td>
            <button name="button" type="submit" class="index_submit delete_submit">
                <%= link_to '削除', note_path(note.id), method: :delete,
                    data: {confirm: '本当に削除していいですか？'} %>
            </button>
        </td>
    </tr>
<% end %>
</table>

app/views/notes/new.html.erb
<h2 class="index">新規投稿</h2>

<%= render 'form' %>

app/views/notes/top.html.erb
<div class="top_area">
    <%= image_tag("top_image.jpg", :class => "top_image") %>
    <p>Welcome t-Note!</p>
</div>